language: dart
dart:
  - stable
  - 2.6.1
  - dev
sudo: required
before_script:
  - source $(pub run chrome_travis:env_rc)
script:
  - dart ./tool/travis.dart
matrix:
  allow_failures:
    - dart: dev