language: dart
dart:
  - stable
  - beta
  - dev
sudo: required
addons:
  chrome: stable
before_script:
  - cd repo_support
  - dart pub get
script:
  - dart ./tool/run_ci.dart
matrix:
  allow_failures:
    - dart: dev