name: dev_test
version: 0.4.2
author: Alexandre Roux @ Tekartik <alex@tekartik.com>
homepage: https://github.com/alextekartik/dev_test.dart
description: Brings (back) the solo and skip features on top of the test package
dependencies:
  test: any