name: dev_test
version: 0.8.0
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/dev_test.dart
description: Brings (back) the solo and skip features on top of the test package
dependencies:
  test: '>= 0.12.5+1'
dev_dependencies:
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart