name: dev_test
version: 0.12.0-dev.0
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/dev_test.dart
description: Brings (back) the solo and skip features on top of the test package

environment:
  sdk: '>=2.0.0-dev.63 <2.0.0'

dependencies:
  test: '>=1.2.0'
  collection: '>=1.14.10'
  stack_trace: '>=1.9.2'

dev_dependencies:
  fs_shim: '>=0.9.0-dev.1'
  browser: any
  process_run: '>=0.6.0-dev.1'
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: dart2
    version: '>=0.8.2'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
