name: dev_test
version: 0.11.1
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/dev_test.dart
description: Brings (back) the solo and skip features on top of the test package

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  test: '>=0.12.29'
  collection: '>=1.14.3'
  stack_trace: any

dev_dependencies:
  fs_shim: '>=0.7.3'
  browser: any
  process_run: '>=0.5.6'
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: dart1
    version: '>=0.8.0'

