name: dev_test
version: 0.9.3
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/dev_test.dart
description: Brings (back) the solo and skip features on top of the test package
environment:
  sdk: '>=1.14.0 <2.0.0'
dependencies:
  test: '>= 0.12.13+5'
  collection: '>=1.4.0'
dev_dependencies:
  fs_shim: any
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
