name: dev_test
version: 0.10.0
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/dev_test.dart
description: Brings (back) the solo and skip features on top of the test package

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  test: '>=0.12.29'
  collection: '>=1.14.3'

dev_dependencies:
  fs_shim: any
  browser: any
  tekartik_pub:
    git: git://github.com/tekartik/pub.dart
    version: '>=0.6.2'

web:
  compiler:
    debug: dartdevc
