name: dev_test
version: 0.15.5+1
homepage: https://github.com/tekartik/dev_test.dart/tree/master/dev_test
description: Brings (back) the solo and skip features on top of the test package

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  test: '>=1.16.2 <3.0.0'
  matcher: '>=0.12.10 <2.0.0'
  collection: '>=1.15.0 <3.0.0'
  stack_trace: '>=1.10.0 <3.0.0'
  process_run: '>=0.12.1 <2.0.0'
  pub_semver: '>=2.0.0 <4.0.0'
  yaml: '>=3.0.0 <5.0.0'
  path: '>=1.8.0 <3.0.0'
  meta: '>=1.3.0 <3.0.0'
  pool: '>=1.5.0 <3.0.0'
  args: '>=2.0.0 <4.0.0'
dev_dependencies:
  fs_shim: '>=2.0.0'
  build_runner: '>=1.11.3'
  build_test: '>=1.3.7'
  build_web_compilers: '>=2.16.4'
  lints: '>=1.0.1'

executables:
  # Run common dart/flutter project testing
  run_ci: