name: dev_test
version: 0.16.2+2
description: Development utilities for dart and flutter packages. CI, build and test helpers.
repository: https://github.com/tekartik/dev_test.dart/tree/master/dev_test

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  test: '>=1.24.6 <3.0.0'
  matcher: '>=0.12.16 <2.0.0'
  collection: '>=1.17.2 <3.0.0'
  stack_trace: '>=1.11.0 <3.0.0'
  process_run: '>=0.13.1 <2.0.0'
  pub_semver: '>=2.1.4 <4.0.0'
  yaml: '>=3.1.2 <5.0.0'
  path: '>=1.8.3 <3.0.0'
  meta: '>=1.9.0 <3.0.0'
  pool: '>=1.5.1 <3.0.0'
  args: '>=2.4.2 <4.0.0'
dev_dependencies:
  build_runner: '>=2.4.6'
  build_test: '>=2.2.0'
  build_web_compilers: '>=4.0.5'
  lints: '>=2.1.1'

executables:
  # Run common dart/flutter project testing
  run_ci:
