name: dev_test
version: 0.15.0-nullsafety.0
homepage: https://github.com/tekartik/dev_test.dart/tree/master/dev_test
description: Brings (back) the solo and skip features on top of the test package

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  test: '>=1.16.0-nullsafety.17 <3.0.0'
  matcher: '>=0.12.10-nullsafety.3 <2.0.0'
  collection: '>=1.15.0-nullsafety.5 <3.0.0'
  stack_trace: '>=1.10.0-nullsafety.6 <3.0.0'
  process_run: '>=0.12.0-nullsafety.0 <2.0.0'
  pub_semver: '>=2.0.0-nullsafety.0 <3.0.0'
  yaml: '>=3.0.0-nullsafety.0 <4.0.0'
  path: '>=1.8.0-nullsafety.3 <3.0.0'
  meta: '>=1.3.0-nullsafety.6 <3.0.0'
  pool: '>=1.5.0-nullsafety.3 <3.0.0'
  args: '>=2.0.0-nullsafety.0 <4.0.0'
dev_dependencies:
  fs_shim: '>=2.0.0-nullsafety.1'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  pedantic: '>=1.10.0-nullsafety.3'

dependency_overrides:
  # Comment for publication - temp nnbd
  # test: '>=1.16.0-nullsafety.11'
  # args: '>=2.0.0-nullsafety.0'
  # pub_semver: '>=2.0.0-nullsafety.0'
executables:
  # Run common dart/flutter project testing
  run_ci: