name: dev_test_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:

dev_dependencies:
  path:
  dev_test:
  lints:
dependency_overrides:
  dev_test:
    path: ../dev_test
